apiVersion: v1
kind: Pod 
metadata:
  name: resource-pod
spec:
  containers:
    - name: redis
      image: redis
      resources:
        requests:
          cpu: 0.5
          memory: 200Mi
          ephemeral-storage: 300Mi
          