apiVersion: v1
kind: Pod 
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.cn-hangzhou.aliyuncs.com/google_containers/busybox
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: CONFIG_MAP_KEY1
          valueFrom:
            configMapKeyRef:
              key: special-hello
              name: special-config
        - name: TEST
          value: "test"

  restartPolicy: Never

